In [1]:
import numpy as np
import pandas as pd

Pivot Tables

In [3]:
data = {
    'Date': pd.date_range('2023-01-01', periods= 20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice'],
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    211     26   John  January      Q1
1  2023-01-02       B   West    357     97   Mary  January      Q1
2  2023-01-03       C  North    314     17    Bob  January      Q1
3  2023-01-04       D  South    430     96  Alice  January      Q1
4  2023-01-05       A   East    972     66   John  January      Q1
5  2023-01-06       B   West    750     26   Mary  January      Q1
6  2023-01-07       C  North    826     76    Bob  January      Q1
7  2023-01-08       D  South    923     36  Alice  January      Q1
8  2023-01-09       A   East    662     89   John  January      Q1
9  2023-01-10       B   West    518     34   Mary  January      Q1
10 2023-01-11       C  North    219     34    Bob  January      Q1
11 2023-01-12       D  South    780     69  Alice  January      Q1
12 2023-01-13       A   East    703     30   John  January      Q1
13 2023-01-14       B   West    738     55   Mary  January      Q1
14 2023-01-15       C  North    335     40    Bob  January      Q1
15 2023-01-16       D  South    182     40  Alice  January      Q1
16 2023-01-17       A   East    288     13   John  January      Q1
17 2023-01-18       B   West    510     70   Mary  January      Q1
18 2023-01-19       C  North    285     13    Bob  January      Q1
19 2023-01-20       D  South    897     44  Alice  January      Q1

In [7]:
pd.pivot_table(df, values = 'Sales', index = 'Region', columns = 'Product')

Product      A      B      C      D
Region
East     567.2    NaN    NaN    NaN
North      NaN    NaN  395.8    NaN
South      NaN    NaN    NaN  642.4
West       NaN  574.6    NaN    NaN

In [9]:
pivot1 = pd.pivot_table(df, values = 'Sales', index = 'Region', columns = 'Product', aggfunc = 'median')
pivot1

Product      A      B      C      D
Region
East     662.0    NaN    NaN    NaN
North      NaN    NaN  314.0    NaN
South      NaN    NaN    NaN  780.0
West       NaN  518.0    NaN    NaN

In [10]:
pivot2 = pd.pivot_table(df, values= ['Sales', 'Units'], index = 'Region', columns = 'Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     567.2    NaN    NaN    NaN  44.8   NaN   NaN   NaN
North      NaN    NaN  395.8    NaN   NaN   NaN  36.0   NaN
South      NaN    NaN    NaN  642.4   NaN   NaN   NaN  57.0
West       NaN  574.6    NaN    NaN   NaN  56.4   NaN   NaN

Cross Tabs

In [12]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0